In [1]:
#Load data from a csv
import csv
import os
import sys

def load_data(filename):
    data = []
    with open(filename , 'r') as f:
        reader = csv.reader(f)
        for row in reader:
            data.append(row)

    return data

def save_data(filename, data):
    with open(filename, 'w') as f:
        writer = csv.writer(f)
        for row in data:
            writer.writerow(row)

In [2]:
import pandas as pd

def build_data_from_csv(filename):
    df = pd.read_csv(filename)
    X = df.iloc[:,1:]  # Excluding the time access
    y = [0]*5000 + [1]*(df.shape[0]-10000) + [0]*5000

    return X, y

In [3]:
X_all = pd.DataFrame()
y_all = []
for file in os.listdir('/kaggle/input/epilepsy-data/dataset/part 1(10 eps)-unfiltered,no ref ch, no G,F,I ch'):
    print(file)
    if file.endswith('.csv'):
        X, y = build_data_from_csv('/kaggle/input/epilepsy-data/dataset/part 1(10 eps)-unfiltered,no ref ch, no G,F,I ch/' + file)
        X_all = pd.concat([X_all, X])
        y_all += y
        

uni_081_Schlick-Reinhard_LMT_no-ref-ch_no-G,F,I-channels.csv
uni_111_Ahmed-Nasteha-Mohamud_LMT_no-ref-ch.csv
uni_125_Erbst-Doris_LMT_no-ref-ch_no-G,F,I-channels.csv
uni_080_Schlick-Reinhard_LMT_no-ref-ch_no-G,F,I-channels.csv
uni_167_Tomic-Stoja_RMT_no-ref-ch.csv
uni_113_Ahmed-Nasteha-Mohamud_RMT_no-ref-ch.csv
uni_112_Ahmed-Nasteha-Mohamud_LMT_no-ref-ch.csv
uni_140_Pott-Eberhand_RMT_no-ref-ch.csv
uni_117_Senzek-Heiko_RMT_no-ref-ch_no-G,F,I-channels.csv


In [4]:
X_all.head()

b'SEEG TBAL3'  b'SEEG TBAL4'  b'SEEG TBPL1'  b'SEEG TBPL2'  b'SEEG TBPL3'  \
0     -11.115209       5.116534      13.379987      -8.879941      -7.946260   
1      -9.510906       7.298814      14.587960      -8.804217      -7.353662   
2      -7.010859      10.011032      15.908634      -7.282950      -5.080339   
3      -5.900975      10.682548      16.272057      -6.450182      -3.630136   
4      -6.201917       9.571956      17.046381      -6.200278      -3.336189   

   b'SEEG TBPL4'  b'SEEG TL01'  b'SEEG TL02'  b'SEEG TL03'  b'SEEG TL04'  ...  \
0       4.697274      0.445759     11.225761    -12.476489    -45.810669  ...   
1       5.572320      4.783992     13.591043    -10.201636    -47.485484  ...   
2       8.193415      5.757773     15.030751     -6.342191    -47.292297  ...   
3       9.559921      3.515125     13.940022     -3.399455    -45.595722  ...   
4       9.201996      1.138111     11.703492     -1.909996    -43.486121  ...   

   b'SEEG TR05'  b'SEEG TR06'  b'SEEG TR07'  b'SEEG TR08'  b'SEEG TR09'  \
0           NaN           NaN           NaN           NaN           NaN   
1           NaN           NaN           NaN           NaN           NaN   
2           NaN           NaN           NaN           NaN           NaN   
3           NaN           NaN           NaN           NaN           NaN   
4           NaN           NaN           NaN           NaN           NaN   

   b'SEEG TR10'  b'SEEG TLR03'  b'SEEG TLR04'  b'SEEG TLR05'  b'SEEG TLR06'  
0           NaN            NaN            NaN            NaN            NaN  
1           NaN            NaN            NaN            NaN            NaN  
2           NaN            NaN            NaN            NaN            NaN  
3           NaN            NaN            NaN            NaN            NaN  
4           NaN            NaN            NaN            NaN            NaN  

[5 rows x 58 columns]

In [5]:
X_all.shape

(394124, 58)

In [6]:
#Repacing all NaN values with 0
X_all = X_all.dropna(axis=1)

In [7]:
# Split the data into training and test sets
from sklearn.model_selection import train_test_split
print("Preparing Data...")
X_train, X_test, y_train, y_test = train_test_split(X_all, y_all, test_size=0.2, random_state=42)



Preparing Data...


In [8]:
!pip install scikit-learn-intelex

In [9]:
from sklearnex import patch_sklearn
patch_sklearn()

Intel(R) Extension for Scikit-learn* enabled (https://github.com/intel/scikit-learn-intelex)


In [10]:
# Print accuracy, precision, recall, f1-score and confusion matrix
from sklearn.metrics import classification_report, confusion_matrix


In [11]:
# Try a different model
from sklearn.ensemble import RandomForestClassifier

print("Loading Model..")
model = RandomForestClassifier()
print("Fitting Model..")
model.fit(X_train, y_train)

model.score(X_test, y_test)


print("Evaluating Model...")
y_pred = model.predict(X_test)

print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))


INFO:sklearnex: sklearn.utils.validation._assert_all_finite: fallback to original Scikit-learn
INFO:sklearnex: sklearn.ensemble.RandomForestClassifier.fit: running accelerated version on CPU
INFO:sklearnex: sklearn.utils.validation._assert_all_finite: fallback to original Scikit-learn
INFO:sklearnex: sklearn.utils.validation._assert_all_finite: running accelerated version on CPU
INFO:sklearnex: sklearn.utils.validation._assert_all_finite: fallback to original Scikit-learn


Loading Model..
Fitting Model..


INFO:sklearnex: sklearn.ensemble.RandomForestClassifier.predict: running accelerated version on CPU
/opt/conda/lib/python3.10/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
INFO:sklearnex: sklearn.utils.validation._assert_all_finite: running accelerated version on CPU
INFO:sklearnex: sklearn.ensemble.RandomForestClassifier.predict: running accelerated version on CPU
/opt/conda/lib/python3.10/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
INFO:sklearnex: sklearn.utils.validation._assert_all_finite: running accelerated version on CPU


Evaluating Model...
              precision    recall  f1-score   support

           0       0.90      0.51      0.65     17908
           1       0.87      0.98      0.92     60917

    accuracy                           0.88     78825
   macro avg       0.89      0.75      0.79     78825
weighted avg       0.88      0.88      0.86     78825

[[ 9217  8691]
 [ 1045 59872]]


In [12]:
from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier()
model.fit(X_train, y_train)

model.score(X_test, y_test)

y_pred = model.predict(X_test)

print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

INFO:sklearnex: sklearn.utils.validation._assert_all_finite: running accelerated version on CPU
INFO:sklearnex: sklearn.neighbors.KNeighborsClassifier.fit: running accelerated version on CPU
INFO:sklearnex: sklearn.utils.validation._assert_all_finite: running accelerated version on CPU
INFO:sklearnex: sklearn.utils.validation._assert_all_finite: fallback to original Scikit-learn
INFO:sklearnex: sklearn.neighbors.KNeighborsClassifier.predict: running accelerated version on CPU
INFO:sklearnex: sklearn.utils.validation._assert_all_finite: running accelerated version on CPU
INFO:sklearnex: sklearn.neighbors.KNeighborsClassifier.predict: running accelerated version on CPU
INFO:sklearnex: sklearn.utils.validation._assert_all_finite: running accelerated version on CPU


              precision    recall  f1-score   support

           0       0.79      0.73      0.76     17908
           1       0.92      0.94      0.93     60917

    accuracy                           0.89     78825
   macro avg       0.86      0.84      0.85     78825
weighted avg       0.89      0.89      0.89     78825

[[13142  4766]
 [ 3521 57396]]


In [13]:
# Train a svm model
from sklearn.svm import SVC
print("Loading Model..")
model = SVC()
print("Fitting Model..")
model.fit(X_train, y_train)

# Evaluate the model
model.score(X_test, y_test)

print("Evaluating Model..")
y_pred = model.predict(X_test)

print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

INFO:sklearnex: sklearn.svm.SVC.fit: running accelerated version on CPU
INFO:sklearnex: sklearn.utils.validation._assert_all_finite: running accelerated version on CPU
INFO:sklearnex: sklearn.utils.validation._assert_all_finite: fallback to original Scikit-learn


Loading Model..
Fitting Model..


INFO:sklearnex: sklearn.svm.SVC.predict: running accelerated version on CPU
INFO:sklearnex: sklearn.utils.validation._assert_all_finite: running accelerated version on CPU
INFO:sklearnex: sklearn.svm.SVC.predict: running accelerated version on CPU
INFO:sklearnex: sklearn.utils.validation._assert_all_finite: running accelerated version on CPU


Evaluating Model..
              precision    recall  f1-score   support

           0       0.97      0.00      0.01     17908
           1       0.77      1.00      0.87     60917

    accuracy                           0.77     78825
   macro avg       0.87      0.50      0.44     78825
weighted avg       0.82      0.77      0.68     78825

[[   60 17848]
 [    2 60915]]


In [15]:
import numpy as np
import pandas as pd

def build_data_from_csv(filename):
    df = pd.read_csv(filename)
    # Create input, labels pairs where input is all columns except the first and output is 0 for first and last 5000 rows and 1 for the rest
    X = df.iloc[:, 1:]
    y = [0] * 5000 + [1] * (df.shape[0] - 10000) + [0] * 5000

    # Splitting indices into train and test sets
    a1 = np.arange(0, 5000)
    a2 = np.arange(5000, df.shape[0] - 5000)
    a3 = np.arange(df.shape[0] - 5000, df.shape[0])

    t1 = list(np.random.choice(a1, int(len(a1) * 0.1), replace=False))
    tr1 = list(set(a1) - set(t1))
    t2 = list(np.random.choice(a2, int(len(a2) * 0.1), replace=False))
    tr2 = list(set(a2) - set(t2))
    t3 = list(np.random.choice(a3, int(len(a3) * 0.1), replace=False))
    tr3 = list(set(a3) - set(t3))

    t = t1 + t2 + t3
    tr = tr1 + tr2 + tr3

    # Splitting data and labels into train and test sets
    test_data = X.iloc[t]
    train_data = X.iloc[tr]
    test_labels = np.array(y)[t]
    train_labels = np.array(y)[tr]
    
    return train_data, test_data, list(train_labels), list(test_labels)


In [17]:
X_train = pd.DataFrame()
X_test = pd.DataFrame()
y_train = []
y_test = []
for file in os.listdir('/kaggle/input/epilepsy-data/dataset/part 1(10 eps)-unfiltered,no ref ch, no G,F,I ch'):
    print(file)
    if file.endswith('.csv'):
        X1, X2, y1, y2 = build_data_from_csv('/kaggle/input/epilepsy-data/dataset/part 1(10 eps)-unfiltered,no ref ch, no G,F,I ch/' + file)
        X_train = pd.concat([X_train, X1])
        X_test = pd.concat([X_test, X2])
        y_train += y1
        y_test += y2
        

uni_081_Schlick-Reinhard_LMT_no-ref-ch_no-G,F,I-channels.csv
uni_111_Ahmed-Nasteha-Mohamud_LMT_no-ref-ch.csv
uni_125_Erbst-Doris_LMT_no-ref-ch_no-G,F,I-channels.csv
uni_080_Schlick-Reinhard_LMT_no-ref-ch_no-G,F,I-channels.csv
uni_167_Tomic-Stoja_RMT_no-ref-ch.csv
uni_113_Ahmed-Nasteha-Mohamud_RMT_no-ref-ch.csv
uni_112_Ahmed-Nasteha-Mohamud_LMT_no-ref-ch.csv
uni_140_Pott-Eberhand_RMT_no-ref-ch.csv
uni_117_Senzek-Heiko_RMT_no-ref-ch_no-G,F,I-channels.csv


In [21]:
#Repacing all NaN values with 0
X_train = X_train.dropna(axis=1)
X_test = X_test.dropna(axis=1)


In [19]:
# Print accuracy, precision, recall, f1-score and confusion matrix
from sklearn.metrics import classification_report, confusion_matrix

In [22]:
from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier()
model.fit(X_train, y_train)

model.score(X_test, y_test)



INFO:sklearnex: sklearn.utils.validation._assert_all_finite: running accelerated version on CPU
INFO:sklearnex: sklearn.neighbors.KNeighborsClassifier.fit: running accelerated version on CPU
INFO:sklearnex: sklearn.utils.validation._assert_all_finite: running accelerated version on CPU
INFO:sklearnex: sklearn.utils.validation._assert_all_finite: fallback to original Scikit-learn
INFO:sklearnex: sklearn.neighbors.KNeighborsClassifier.predict: running accelerated version on CPU
INFO:sklearnex: sklearn.utils.validation._assert_all_finite: running accelerated version on CPU


0.9011089400360343

In [23]:
y_pred = model.predict(X_test)

print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

INFO:sklearnex: sklearn.neighbors.KNeighborsClassifier.predict: running accelerated version on CPU
INFO:sklearnex: sklearn.utils.validation._assert_all_finite: running accelerated version on CPU


              precision    recall  f1-score   support

           0       0.80      0.75      0.78      9000
           1       0.93      0.95      0.94     30407

    accuracy                           0.90     39407
   macro avg       0.87      0.85      0.86     39407
weighted avg       0.90      0.90      0.90     39407

[[ 6750  2250]
 [ 1647 28760]]


In [24]:
# Try a different model
from sklearn.ensemble import RandomForestClassifier

print("Loading Model..")
model = RandomForestClassifier()
print("Fitting Model..")
model.fit(X_train, y_train)

model.score(X_test, y_test)


print("Evaluating Model...")
y_pred = model.predict(X_test)

print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))


INFO:sklearnex: sklearn.utils.validation._assert_all_finite: fallback to original Scikit-learn
INFO:sklearnex: sklearn.ensemble.RandomForestClassifier.fit: running accelerated version on CPU
INFO:sklearnex: sklearn.utils.validation._assert_all_finite: fallback to original Scikit-learn
INFO:sklearnex: sklearn.utils.validation._assert_all_finite: running accelerated version on CPU
INFO:sklearnex: sklearn.utils.validation._assert_all_finite: fallback to original Scikit-learn


Loading Model..
Fitting Model..


INFO:sklearnex: sklearn.ensemble.RandomForestClassifier.predict: running accelerated version on CPU
/opt/conda/lib/python3.10/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
INFO:sklearnex: sklearn.utils.validation._assert_all_finite: running accelerated version on CPU
INFO:sklearnex: sklearn.ensemble.RandomForestClassifier.predict: running accelerated version on CPU
/opt/conda/lib/python3.10/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
INFO:sklearnex: sklearn.utils.validation._assert_all_finite: running accelerated version on CPU


Evaluating Model...
              precision    recall  f1-score   support

           0       0.90      0.53      0.67      9000
           1       0.88      0.98      0.93     30407

    accuracy                           0.88     39407
   macro avg       0.89      0.76      0.80     39407
weighted avg       0.88      0.88      0.87     39407

[[ 4795  4205]
 [  531 29876]]


In [25]:
# Train a svm model
from sklearn.svm import SVC
print("Loading Model..")
model = SVC()
print("Fitting Model..")
model.fit(X_train, y_train)

# Evaluate the model
model.score(X_test, y_test)

print("Evaluating Model..")
y_pred = model.predict(X_test)

print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

INFO:sklearnex: sklearn.svm.SVC.fit: running accelerated version on CPU
INFO:sklearnex: sklearn.utils.validation._assert_all_finite: running accelerated version on CPU
INFO:sklearnex: sklearn.utils.validation._assert_all_finite: fallback to original Scikit-learn


Loading Model..
Fitting Model..


INFO:sklearnex: sklearn.svm.SVC.predict: running accelerated version on CPU
INFO:sklearnex: sklearn.utils.validation._assert_all_finite: running accelerated version on CPU
INFO:sklearnex: sklearn.svm.SVC.predict: running accelerated version on CPU
INFO:sklearnex: sklearn.utils.validation._assert_all_finite: running accelerated version on CPU


Evaluating Model..
              precision    recall  f1-score   support

           0       1.00      0.01      0.01      9000
           1       0.77      1.00      0.87     30407

    accuracy                           0.77     39407
   macro avg       0.89      0.50      0.44     39407
weighted avg       0.82      0.77      0.67     39407

[[   45  8955]
 [    0 30407]]
